// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Snap.Hutao.Server.Model.Context;

#nullable disable

namespace Snap.Hutao.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221016111027_ChangeKeyType")]
    partial class ChangeKeyType
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Snap.Hutao.Server.Model.Entity.EntityAvatar", b =>
                {
                    b.Property<long>("PrimaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<int>("ActivedConstellationNumber")
                        .HasColumnType("int");

                    b.Property<int>("AvatarId")
                        .HasColumnType("int");

                    b.Property<long>("RecordId")
                        .HasColumnType("bigint");

                    b.Property<string>("ReliquarySet")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("WeaponId")
                        .HasColumnType("int");

                    b.HasKey("PrimaryId");

                    b.HasIndex("RecordId");

                    b.ToTable("avatars");
                });

            modelBuilder.Entity("Snap.Hutao.Server.Model.Entity.EntityDamageRank", b =>
                {
                    b.Property<long>("PrimaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<int>("AvatarId")
                        .HasColumnType("int");

                    b.Property<long>("SpiralAbyssId")
                        .HasColumnType("bigint");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("PrimaryId");

                    b.HasIndex("SpiralAbyssId")
                        .IsUnique();

                    b.HasIndex("Value");

                    b.ToTable("damage_ranks");
                });

            modelBuilder.Entity("Snap.Hutao.Server.Model.Entity.EntityFloor", b =>
                {
                    b.Property<long>("PrimaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<string>("Levels")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("SpiralAbyssId")
                        .HasColumnType("bigint");

                    b.Property<int>("Star")
                        .HasColumnType("int");

                    b.HasKey("PrimaryId");

                    b.HasIndex("SpiralAbyssId");

                    b.ToTable("spiral_abysses_floors");
                });

            modelBuilder.Entity("Snap.Hutao.Server.Model.Entity.EntityRecord", b =>
                {
                    b.Property<long>("PrimaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("varchar(9)");

                    b.Property<long>("UploadTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Uploader")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("PrimaryId");

                    b.ToTable("records");
                });

            modelBuilder.Entity("Snap.Hutao.Server.Model.Entity.EntitySpiralAbyss", b =>
                {
                    b.Property<long>("PrimaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("RecordId")
                        .HasColumnType("bigint");

                    b.HasKey("PrimaryId");

                    b.HasIndex("RecordId")
                        .IsUnique();

                    b.ToTable("spiral_abysses");
                });

            modelBuilder.Entity("Snap.Hutao.Server.Model.Entity.EntityTakeDamageRank", b =>
                {
                    b.Property<long>("PrimaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<int>("AvatarId")
                        .HasColumnType("int");

                    b.Property<long>("SpiralAbyssId")
                        .HasColumnType("bigint");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("PrimaryId");

                    b.HasIndex("SpiralAbyssId")
                        .IsUnique();

                    b.HasIndex("Value");

                    b.ToTable("take_damage_ranks");
                });

            modelBuilder.Entity("Snap.Hutao.Server.Model.Entity.LegacyStatistics", b =>
                {
                    b.Property<long>("PrimaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int");

                    b.HasKey("PrimaryId");

                    b.ToTable("spiral_abysses_statistics");
                });

            modelBuilder.Entity("Snap.Hutao.Server.Model.Entity.RequestStatistics", b =>
                {
                    b.Property<long>("PrimaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("Count")
                        .HasColumnType("bigint");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("PrimaryId");

                    b.ToTable("request_statistics");
                });

            modelBuilder.Entity("Snap.Hutao.Server.Model.Entity.EntityAvatar", b =>
                {
                    b.HasOne("Snap.Hutao.Server.Model.Entity.EntityRecord", "Record")
                        .WithMany("Avatars")
                        .HasForeignKey("RecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Record");
                });

            modelBuilder.Entity("Snap.Hutao.Server.Model.Entity.EntityDamageRank", b =>
                {
                    b.HasOne("Snap.Hutao.Server.Model.Entity.EntitySpiralAbyss", "SpiralAbyss")
                        .WithOne("Damage")
                        .HasForeignKey("Snap.Hutao.Server.Model.Entity.EntityDamageRank", "SpiralAbyssId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SpiralAbyss");
                });

            modelBuilder.Entity("Snap.Hutao.Server.Model.Entity.EntityFloor", b =>
                {
                    b.HasOne("Snap.Hutao.Server.Model.Entity.EntitySpiralAbyss", "SpiralAbyss")
                        .WithMany("Floors")
                        .HasForeignKey("SpiralAbyssId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SpiralAbyss");
                });

            modelBuilder.Entity("Snap.Hutao.Server.Model.Entity.EntitySpiralAbyss", b =>
                {
                    b.HasOne("Snap.Hutao.Server.Model.Entity.EntityRecord", "Record")
                        .WithOne("SpiralAbyss")
                        .HasForeignKey("Snap.Hutao.Server.Model.Entity.EntitySpiralAbyss", "RecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Record");
                });

            modelBuilder.Entity("Snap.Hutao.Server.Model.Entity.EntityTakeDamageRank", b =>
                {
                    b.HasOne("Snap.Hutao.Server.Model.Entity.EntitySpiralAbyss", "SpiralAbyss")
                        .WithOne("TakeDamage")
                        .HasForeignKey("Snap.Hutao.Server.Model.Entity.EntityTakeDamageRank", "SpiralAbyssId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SpiralAbyss");
                });

            modelBuilder.Entity("Snap.Hutao.Server.Model.Entity.EntityRecord", b =>
                {
                    b.Navigation("Avatars");

                    b.Navigation("SpiralAbyss");
                });

            modelBuilder.Entity("Snap.Hutao.Server.Model.Entity.EntitySpiralAbyss", b =>
                {
                    b.Navigation("Damage")
                        .IsRequired();

                    b.Navigation("Floors");

                    b.Navigation("TakeDamage")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
