// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Snap.Hutao.Server.Migrations
{
    /// <inheritdoc />
    public partial class ChangeRedeemCodeUseItemToUseUserId : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "UseBy",
                table: "redeem_code_use_items");

            migrationBuilder.AddColumn<int>(
                name: "UsedBy",
                table: "redeem_code_use_items",
                type: "int",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.CreateIndex(
                name: "IX_redeem_code_use_items_UsedBy",
                table: "redeem_code_use_items",
                column: "UsedBy");

            migrationBuilder.AddForeignKey(
                name: "FK_redeem_code_use_items_AspNetUsers_UsedBy",
                table: "redeem_code_use_items",
                column: "UsedBy",
                principalTable: "AspNetUsers",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_redeem_code_use_items_AspNetUsers_UsedBy",
                table: "redeem_code_use_items");

            migrationBuilder.DropIndex(
                name: "IX_redeem_code_use_items_UsedBy",
                table: "redeem_code_use_items");

            migrationBuilder.DropColumn(
                name: "UsedBy",
                table: "redeem_code_use_items");

            migrationBuilder.AddColumn<string>(
                name: "UseBy",
                table: "redeem_code_use_items",
                type: "longtext",
                nullable: false)
                .Annotation("MySql:CharSet", "utf8mb4");
        }
    }
}
