version: '3.8'

services:
  homa-server:
    build:
      context: .
      dockerfile: Dockerfile
      target: final
    image: homa-server:latest
    extra_hosts:
      host.docker.internal: 172.27.0.1
    container_name: Homa-Server
    volumes:
      - ./.env:/app/.env
    restart: unless-stopped
    depends_on:
      - redis
    extra_hosts:
      - "host.docker.internal:host-gateway"

  redis:
    container_name: Homa-Server-Redis
    image: redis:latest
    volumes:
      - ./redis:/data
    restart: unless-stopped